import Head from "next/head";
import styles from "../styles/Home.module.css";
import Map from "../components/GoogleMap";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>“Jingle All The Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Jingle All The Way</h1>
        <Map />
      </main>
    </div>
  );
}
